apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-keyvault-sync
  namespace: database-ns
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "12508931-9f88-4058-aab9-74135105fbff" # L'ID client de l'identité managée créée par Terraform (récupérer la valeur dans les logs de pipeline Terraform)
    keyvaultName: "kv-ads-nonpro-9f71" # Le nom du Key Vault créé par Terraform
    tenantId: "a2e466aa-4f86-4545-b5b8-97da7c8febf3" # L'ID du tenant Azure (récupérer la valeur dans les logs de pipeline Terraform)
    objects:  |
      array:
        - |
          objectName: mysql-root-password # Le nom du secret tel qu'il sera créé dans le Key Vault
          objectType: secret
          objectVersion: ""