apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: database-ns
  annotations:
    # L'ID client de l'identité managée créée par Terraform (récupérer la valeur dans les logs de pipeline Terraform)
    azure.workload.identity/client-id: "f24f7ce4-8cbe-41d3-87fb-7c89908e3553"