apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: database-ns
  annotations:
    # L'ID client de l'identité managée créée par Terraform (récupérer la valeur dans les logs de pipeline Terraform)
    azure.workload.identity/client-id: "34f92443-ad07-4086-b9b6-5fb78d6e2cd0"