apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: database-ns
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    # Sélecteur pour associer le service aux pods MySQL
    app: mysql